from tkinter import CENTER


FONT_TIMES = "Times"

FONT_TIMES_12 = (FONT_TIMES, 12)
FONT_TIMES_14 = (FONT_TIMES, 14)
FONT_TIMES_20 = (FONT_TIMES, 20)

PRIMARY = "#20063B"
WHITE = "#FFFFFF"

CENTER = CENTER

RELIEF_FLAT = "flat"

ERROR_MESSAGE_INVALID_VALUES = "YOU NEED TO INPUT CORRECT VALUES."